### ISSUE TITLE
manifest 오류로 문의드립니다. 

### ISSUE THREAD

**Issue by junog115** [godofjava/GodOfJava2nd#1]
안녕하세요 
자바의 신으로 자바를 공부하게 된 학생입니다. 
다름이 아니라 자바 코드 실행기를 실행해봤는데, manifest 속성이 없다는 오류가 나서 이렇게 문의를 드립니다. 

java -version 의 결과는

java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
로 나오고, 

자바 코드 실행기의 실행 결과는 

$ java -jar godofjava-180310.jar

godofjava-180310.jar에 기본 Manifest 속성이 없습니다.
라고 나옵니다.

**Comment by junog115** [comment]
아 혹시나 해서 java 8 버전에서 실행하라고 하신 파일도 실행해 보았으나 실행되지 않았습니다. 

실행 결과는 다음과 같습니다. 

$ java -jar godofjava-170619.jar

Exception in Application start method
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.godofjava.GodOfJavaMain.start(GodOfJavaMain.java:27)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        ... 1 more
Exception running application com.godofjava.GodOfJavaMain

**Comment by godofjava** [comment]
제가 빌드를 잘못해서 올렸네요. 
JavaFX 가 빌드하는게 좀 복잡하거든요. - -;

다시 새 버전 받으셔서 수행하시면 잘 될겁니다.

**Comment by junog115** [comment]
잘되네요 금방 고쳐주셔서 감사합니다.
